# Generated by Django 5.1.3 on 2025-02-04 05:42

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('offer_text_with_link', models.TextField(blank=True, help_text='Offer text with link in html format', null=True)),
                ('manufacturer_text', models.TextField(blank=True, help_text='Manufacturer text in html format use <span> tag for highlighting', null=True)),
                ('manufacturer_video', models.FileField(blank=True, help_text='Manufacturer video', null=True, upload_to='home/')),
                ('deals_banner_1', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Deals banner 1', null=True, upload_to='home/')),
                ('deals_banner_2', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Deals banner 2', null=True, upload_to='home/')),
                ('deals_banner_1_link', models.URLField(blank=True, help_text='Deals banner 1 link', null=True)),
                ('deals_banner_2_link', models.URLField(blank=True, help_text='Deals banner 2 link', null=True)),
                ('retail_background', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Retail background', null=True, upload_to='home/')),
                ('retail_text', models.TextField(blank=True, help_text='Retail text in html format', null=True)),
                ('retail_link', models.URLField(blank=True, help_text='Retail link', null=True)),
                ('seo_meta_title', models.CharField(blank=True, max_length=70, null=True)),
                ('seo_meta_description', models.CharField(blank=True, max_length=160, null=True)),
                ('seo_meta_keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_seo', models.TextField(blank=True, help_text='Additional SEO code or metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('position', models.PositiveIntegerField(unique=True)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='slider/')),
            ],
        ),
    ]
