# Generated by Django 5.1.3 on 2025-02-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name_plural': 'Home Page'},
        ),
        migrations.CreateModel(
            name='VideoCallBooking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('slot', models.CharField(choices=[('09:00-09:30', '09:00 AM - 09:30 AM'), ('09:30-10:00', '09:30 AM - 10:00 AM'), ('10:00-10:30', '10:00 AM - 10:30 AM'), ('10:30-11:00', '10:30 AM - 11:00 AM'), ('11:00-11:30', '11:00 AM - 11:30 AM'), ('11:30-12:00', '11:30 AM - 12:00 PM'), ('12:00-12:30', '12:00 PM - 12:30 PM'), ('12:30-13:00', '12:30 PM - 01:00 PM'), ('13:00-13:30', '01:00 PM - 01:30 PM'), ('13:30-14:00', '01:30 PM - 02:00 PM'), ('14:00-14:30', '02:00 PM - 02:30 PM'), ('14:30-15:00', '02:30 PM - 03:00 PM'), ('15:00-15:30', '03:00 PM - 03:30 PM'), ('15:30-16:00', '03:30 PM - 04:00 PM'), ('16:00-16:30', '04:00 PM - 04:30 PM'), ('16:30-17:00', '04:30 PM - 05:00 PM')], max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Video Call Booking',
                'unique_together': {('date', 'slot')},
            },
        ),
    ]
