# Generated by Django 5.1.3 on 2025-02-06 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_product_seller_pdf'),
        ('website', '0002_alter_home_options_videocallbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocallbooking',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
            preserve_default=False,
        ),
    ]
