# Generated by Django 5.1.3 on 2024-11-09 07:37

import colorfield.fields
import django.db.models.deletion
import inventory.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(upload_to='category_thumbnails/', validators=[inventory.validators.validate_thumbnail_size])),
                ('seo_meta_title', models.CharField(blank=True, max_length=70, null=True)),
                ('seo_meta_description', models.CharField(blank=True, max_length=160, null=True)),
                ('seo_meta_keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_seo', models.TextField(blank=True, help_text='Additional SEO code or metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'indexes': [models.Index(fields=['slug'], name='inventory_c_slug_9e1826_idx'), models.Index(fields=['created_at'], name='inventory_c_created_c7d6f1_idx'), models.Index(fields=['updated_at'], name='inventory_c_updated_c57bcf_idx')],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'Flat')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('usage_limit', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
                'indexes': [models.Index(fields=['code'], name='inventory_d_code_bdc92a_idx'), models.Index(fields=['start_date'], name='inventory_d_start_d_f397e3_idx'), models.Index(fields=['end_date'], name='inventory_d_end_dat_b16995_idx'), models.Index(fields=['created_at'], name='inventory_d_created_9bb707_idx'), models.Index(fields=['updated_at'], name='inventory_d_updated_42b0d0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.discount')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
            },
        ),
        migrations.CreateModel(
            name='DiscountHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inventory.discount')),
            ],
            options={
                'verbose_name': 'Discount History',
                'verbose_name_plural': 'Discount Histories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='product_thumbnails/', validators=[inventory.validators.validate_thumbnail_size])),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('tax', models.FloatField(default=0)),
                ('seo_meta_title', models.CharField(blank=True, max_length=70, null=True)),
                ('seo_meta_description', models.CharField(blank=True, max_length=160, null=True)),
                ('seo_meta_keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_seo', models.TextField(blank=True, help_text='Additional SEO code or metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('is_verified', models.BooleanField(default=False)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='inventory.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Review',
                'verbose_name_plural': 'Product Reviews',
            },
        ),
        migrations.CreateModel(
            name='ProductShipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_method', models.CharField(max_length=100)),
                ('local_shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('regional_shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('national_shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_cost_multiply_quantity', models.BooleanField(default=False)),
                ('estimated_delivery_time', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_shipping_info', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_details', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Product Shipping',
                'verbose_name_plural': 'Product Shippings',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('name', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('is_main', models.BooleanField(default=False, help_text='Indicates if this is the main image for the product.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.productvariant')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='inventory.productvariant')),
            ],
            options={
                'verbose_name': 'Price History',
                'verbose_name_plural': 'Price Histories',
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('in', 'In'), ('out', 'Out')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transactions', to='inventory.productvariant')),
            ],
            options={
                'verbose_name': 'Inventory Transaction',
                'verbose_name_plural': 'Inventory Transactions',
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='review_photos/', validators=[inventory.validators.validate_thumbnail_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.productreview')),
            ],
            options={
                'verbose_name': 'Review Image',
                'verbose_name_plural': 'Review Images',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('seo_meta_title', models.CharField(blank=True, max_length=70, null=True)),
                ('seo_meta_description', models.CharField(blank=True, max_length=160, null=True)),
                ('seo_meta_keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_seo', models.TextField(blank=True, help_text='Additional SEO code or metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='inventory.category')),
            ],
            options={
                'verbose_name': 'Subcategory',
                'verbose_name_plural': 'Subcategories',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.subcategory'),
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='inventory.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coupon Usage',
                'verbose_name_plural': 'Coupon Usages',
                'indexes': [models.Index(fields=['coupon'], name='inventory_c_coupon__9ef1e9_idx'), models.Index(fields=['user'], name='inventory_c_user_id_6ea603_idx'), models.Index(fields=['created_at'], name='inventory_c_created_5f6084_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code'], name='inventory_c_code_ddb0f8_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_active'], name='inventory_c_is_acti_a0f147_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['created_at'], name='inventory_c_created_784f6b_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['updated_at'], name='inventory_c_updated_855824_idx'),
        ),
        migrations.AddIndex(
            model_name='discounthistory',
            index=models.Index(fields=['discount'], name='inventory_d_discoun_ec28a5_idx'),
        ),
        migrations.AddIndex(
            model_name='discounthistory',
            index=models.Index(fields=['timestamp'], name='inventory_d_timesta_383c2f_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product'], name='inventory_p_product_8d93ab_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['user'], name='inventory_p_user_id_96c63f_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['rating'], name='inventory_p_rating_5b91a4_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['created_at'], name='inventory_p_created_43715d_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['updated_at'], name='inventory_p_updated_eb1cd9_idx'),
        ),
        migrations.AddIndex(
            model_name='productshipping',
            index=models.Index(fields=['product'], name='inventory_p_product_8d9390_idx'),
        ),
        migrations.AddIndex(
            model_name='productshipping',
            index=models.Index(fields=['shipping_method'], name='inventory_p_shippin_3c0f89_idx'),
        ),
        migrations.AddIndex(
            model_name='productshipping',
            index=models.Index(fields=['created_at'], name='inventory_p_created_594f01_idx'),
        ),
        migrations.AddIndex(
            model_name='productshipping',
            index=models.Index(fields=['updated_at'], name='inventory_p_updated_d52d88_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['sku'], name='inventory_p_sku_3e98d7_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product'], name='inventory_p_product_cc68de_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['created_at'], name='inventory_p_created_1d19a8_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['updated_at'], name='inventory_p_updated_322023_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product_variant'], name='inventory_p_product_ace2a2_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['is_main'], name='inventory_p_is_main_866e6a_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['created_at'], name='inventory_p_created_6a9a25_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['updated_at'], name='inventory_p_updated_ca88e0_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['product_variant'], name='inventory_p_product_5cb317_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['timestamp'], name='inventory_p_timesta_39a207_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['product_variant'], name='inventory_i_product_b6edc2_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['created_at'], name='inventory_i_created_670884_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewimage',
            index=models.Index(fields=['review'], name='inventory_r_review__5b48bd_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewimage',
            index=models.Index(fields=['uploaded_at'], name='inventory_r_uploade_8812a6_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['slug'], name='inventory_s_slug_8e6990_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['category'], name='inventory_s_categor_0f8dc9_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['created_at'], name='inventory_s_created_f0b053_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['updated_at'], name='inventory_s_updated_3c9610_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='inventory_p_slug_d7b9f5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='inventory_p_sku_f85905_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='inventory_p_categor_607069_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['subcategory'], name='inventory_p_subcate_f169b5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='inventory_p_created_081871_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['updated_at'], name='inventory_p_updated_ec265f_idx'),
        ),
    ]
