# Generated by Django 5.1.3 on 2024-11-11 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='discount',
            name='inventory_d_code_bdc92a_idx',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='code',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.discount'),
        ),
    ]
