# Generated by Django 5.1.3 on 2024-11-11 11:13

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_coupon_options_alter_couponusage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(upload_to='category_thumbnails/'),
        ),
    ]
