# Generated by Django 5.1.3 on 2024-11-14 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_productfaq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productfaq',
            options={'verbose_name': 'Product FAQ', 'verbose_name_plural': 'Product FAQs'},
        ),
    ]
