# Generated by Django 5.1.3 on 2024-11-14 09:29

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_productfaq_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='category_thumbnails/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='category_thumbnails/'),
        ),
    ]
