# Generated by Django 5.1.3 on 2024-11-14 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_product_thumbnail_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
    ]
