# Generated by Django 5.1.3 on 2025-01-07 05:41

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_product_stock_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='inventory_p_sku_3e98d7_idx',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='sku',
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.color'),
        ),
    ]
