# Generated by Django 5.1.3 on 2025-01-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_productvariant_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=550, max_digits=10),
            preserve_default=False,
        ),
    ]
