# Generated by Django 5.1.3 on 2025-01-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller_pdf',
            field=models.FileField(blank=True, null=True, upload_to='seller_pdfs/'),
        ),
    ]
